version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:

  build:
    commands:
      - apt-get update -y
      - apt-get install -y docker.io

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 337909784521.dkr.ecr.eu-north-1.amazonaws.com
      
      - echo "Building the Docker image..."
      - docker build -t doc .
      
      - docker tag doc:latest 337909784521.dkr.ecr.eu-north-1.amazonaws.com/doc:latest
      - echo "Pushing the Docker image to ECR..."
      - docker push 337909784521.dkr.ecr.eu-north-1.amazonaws.com/doc:latest

      - | 
        echo '[
        {
          "name": "newcontainer",
          "imageUri": "490004642561.dkr.ecr.eu-north-1.amazonaws.com/docker-repo:latest"
          }
        ]' >imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json